name: Build and Push Image

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: 
      - 'main'

jobs:
  go-test:
    strategy:
      matrix:
        go-version: [1.20]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...

  dotenv:
    needs: [go-test]
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Generate dotenv for go
        shell: bash 
        run: |
          {
            echo USER_DB="${{ secrets.SECRET_USER_DB }}"
            echo PASSWORD_DB="${{ secrets.SECRET_PASSWORD_DB }}"
            echo HOST_DB="${{ secrets.SECRET_HOST_DB }}"
            echo PORT_DB="${{ secrets.SECRET_PORT_DB }}"
            echo NAME_DB="${{ secrets.SECRET_NAME_DB }} "
            echo SECRET_JWT="${{ secrets.SECRET_PASSWORD_DB }}"
            echo SESSION_TOKEN="${{ secrets.SECRET_SESSION_TOKEN }}"
          } > .env
      -
        name: Check the content
        run: | 
          cat .env
      - 
        name: Upload dotenv result
        uses: actions/upload-artifact@v2
        with:
          name: dotenv
          path: .env
  
  docker:
    needs: [dotenv, go-test]
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Download dotenv result
        uses: actions/download-artifact@v2
        with:
          name: dotenv
      - 
        name: Print the content
        shell: bash
        run: cat .env
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          repository: dall06/go_api_image
          file: docker/Dockerfile.prod
          tags: dall06/go_cc_api_image:latest